#!/bin/bash

ARGS=$#
PARAMS=""
while (( "$#" )); do
    case "$1" in
        -Y|--yaml)
            FILE=$2
            shift
            ;;
        -n|--name)
            HWNUM=$2
            shift
            ;;
        -h|--help)
            printf "ga [-Y] [input-file]\n-h,--help for help\n"
            shift
            ;;
        -*|--*=) # unsupported flags
            echo "Error: Unsupported flag $1" >&2
            exit 1
            ;;
        *) #reserve positional arguments
            PARAMS="$PARAMS $1"
            shift
            ;;
    esac
done

info() {
    echo "[${CYAN}INFO${NC}]" "$@"
}

warn() {
    echo "[${RED}ERROR${NC}]" "$@"
}

setup_color() {
    RED=$(printf '\033[0;31m')
    CYAN=$(printf '\033[0;36m')
    ORANGE=$(printf '\033[0;33m')
    NC=$(printf '\033[0m')
}

get_template() {
    info "autograde-Makefile"
    curl -o ./autograde-Makefile -fsSL https://github.com/WesleyCh3n/NTUBME-Autograde/raw/master/template/autograde-Makefile.template
    info "gtest.cpp.template"
    curl -o ./gtest.cpp -fsSL https://github.com/WesleyCh3n/NTUBME-Autograde/raw/master/template/gtest.cpp.template
    info "score.py"
    curl -o ./score.py -fsSL https://github.com/WesleyCh3n/NTUBME-Autograde/raw/master/template/score.py.template
}

parse_yml() {
    # HW name
    HW=$(yq -r ".Autograde.Homework" ${FILE})
    NUM=$(echo $HW | tr -dc '0-9')
    PRO=$(echo $HW | tr -d '0-9')
    HW_NUM=$(printf "%02d%s" $NUM $PRO)
    echo "Homework number: ${HW_NUM^^}"

    # Variable Type
    L_TYPE=$(yq -r ".Autograde.VariableType | length" ${FILE})
    if [[ $L_TYPE == 0 ]];then
        echo "no variable declared"
    else
        TYPES=($(yq -r ".Autograde.VariableType | @sh" ${FILE}))
        echo "Total Variables: ${TYPES[@]}"|tr -d "'"
    fi

    # Google Test Variable
    ## Length of the test
    L_TEST=$(yq -r ".Autograde.Test | length" ${FILE})
    ## INPUT
    if [[ $L_TEST == 0 ]];then
        echo "There is no test"
    else
        echo "There are $L_TEST tests"
        INPUTS=$(yq -r ".Autograde.Test[].input" ${FILE})
        # echo $INPUTS
        if [[ $INPUTS == "null" ]];then
            echo "There is no inputs for tests."
            FINAL_INPUT=""
        else
            FINAL_INPUT=""
            for((i=0; i<$((L_TEST)); i++));do
                INPUT=$(yq -r ".Autograde.Test[$((i))].input|@sh" ${FILE})

                if [[ $INPUT == "null" ]];then
                    FINAL_INPUT+=";"
                else
                    FINAL_INPUT+="$INPUT;"
                fi
            done
        fi
    fi
    echo "Inputs: $FINAL_INPUT"

    for((i=0; i<$((L_TEST)); i++));do
        TEST_ANSWER=""
        L_ANSWER=$(yq -r ".Autograde.Test[$((i))].answer|length" ${FILE})
        for((j=0; j<$((L_ANSWER)); j++));do
            L=$(yq -r ".Autograde.Test[$((i))].answer[$((j))].L" ${FILE})
            L=$(echo $L | sed "s/ans/answer/g")
            op=$(yq -r ".Autograde.Test[$((i))].answer[$((j))].op" ${FILE})
            R=$(yq -r ".Autograde.Test[$((i))].answer[$((j))].R" ${FILE})
            TEST_ANSWER+="$L$op$R\n"
        done
        printf "Testing $((i+1))\n$TEST_ANSWER"
    done
}

makefile() {
    sed -i "s/{{HW_NUM}}/${HW_NUM^^}/" "$@"
    sed -i "s/{{N_TEST}}/$((L_TEST))/" "$@"
    sed -i "s/{{INPUTS}}/\"${FINAL_INPUT}\"/" "$@"
}

gtest() {
    # Decalre ansers with type in gtest.cpp
    for((i=0; i<$((L_TYPE)); i++));do
        sed -i "$((i+3))a extern $(echo ${TYPES[i]}|tr -d "'") answer$((i+1));" "$@"
    done

    for((i=0; i<$((L_TEST)); i++));do
        FUNC=""
        L_ANSWER=$(yq -r ".Autograde.Test[$((i))].answer|length" ${FILE})
        for((j=0; j<$((L_ANSWER)); j++));do
            L=$(yq -r ".Autograde.Test[$((i))].answer[$((j))].L" ${FILE})
            L=$(echo $L | sed "s/ans/answer/g")
            op=$(yq -r ".Autograde.Test[$((i))].answer[$((j))].op" ${FILE})
            R=$(yq -r ".Autograde.Test[$((i))].answer[$((j))].R" ${FILE})
            if [[ ${op} == "=" ]];then
                FUNC+="\tASSERT_EQ(${L}, ${R});\n"

            elif [[ ${op} == ">" ]];then
                FUNC+="\tASSERT_GT(${L}, ${R});\n"

            elif [[ ${op} == "<" ]];then
                FUNC+="\tASSERT_LT(${L}, ${R});\n"

            elif [[ ${op} == "!=" ]];then
                FUNC+="\tASSERT_NE(${L}, ${R});\n"

            elif [[ ${op} == ">=" ]];then
                FUNC+="\tASSERT_GE(${L}, ${R});\n"

            elif [[ ${op} == "<=" ]];then
                FUNC+="\tASSERT_LE(${L}, ${R});\n"

            elif [[ ${op} == "&=" ]];then
                FUNC+="\tASSERT_STREQ(${L}, \"${R}\");\n"

            elif [[ ${op} == "&?" ]];then
                FUNC+="\tASSERT_STRNE(${L}, \"${R}\");\n"
            fi
        done
        STR="\nTEST(GoogleTest, test$((i+1))){\n${FUNC}}"
        echo -e ${STR} >> "$@"
    done
}

create(){
    if [[ $HWNUM != "" ]];then
        FILENAME="-HW0${HWNUM^^}"
    else
        FILENAME=""
    fi

    echo -e "\
---
Autograde:
  Homework: $HWNUM
  VariableType: []
  Test:
    - input: []
      answer:
        - L:
          op: ''
          R:" > answers$FILENAME.yml
}

{
    setup_color
    if [[ $ARGS != 0 ]];then
        if [[ $FILE != "" ]];then
            info "getting latest template"
            get_template
            info "parsing yml"
            parse_yml
            info "creating autograde-Makefile"
            makefile "./autograde-Makefile"
            info "creating gtest.cpp"
            gtest "./gtest.cpp"
            info "tar autograde.tar"
            tar cf autograde.tar ./gtest.cpp ./score.py
            rm ./gtest.cpp ./score.py
        elif [[ $HWNUM != "" ]];then
            if [[ -f "./answers.yml" ]]; then
                warn "answers.yml exists. Abort..."
            else
                create
            fi
        fi
    else
        info "generate yaml sample"
        if [[ -f "./answers.yml" ]]; then
            warn "answers.yml exists. Abort..."
        else
            create
        fi
    fi
}

